# For more information:
# https://laravel.com/docs/sail
version: '3'

services:
  laravel.test:
    build:
      context: ./vendor/laravel/sail/runtimes/8.0
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.0/app
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - postgres
      - redis
    #  - selenium

  postgres:
    image: postgres
    networks:
      - sail
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    volumes:
      - sailpostgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'

  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'sailredis:/data'
    networks:
      - sail

  # memcached:
  #     image: 'memcached:alpine'
  #     ports:
  #         - '11211:11211'
  #     networks:
  #         - sail

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - sail

  #  selenium:
  #    image: 'selenium/standalone-chrome'
  #    volumes:
  #      - '/dev/shm:/dev/shm'
  #    networks:
  #      - sail

networks:
  sail:
    driver: bridge

volumes:
  sailpostgres:
    driver: local

  sailredis:
    driver: local
